version: "3"
services: 
  postgres:
    image: "postgres:11"
    ports: 
      - $POSTGRES_DB_PORT:$POSTGRES_DB_PORT
    env_file: 
      - .env
    environment: 
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
    volumes: 
      - postgres-black-box-db:/var/lib/postgresql/data
volumes: 
  postgres-black-box-db:
    driver: local